services:
  - type: web
    name: vigoblue
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_SSL
        value: "true"
      - key: DB_NAME
        value: VigoBlue
      - key: SESSION_SECRET
        generateValue: true
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: STRIPE_SECRET
        sync: false
